# Module 03: Intro to NumPy

Follow along here during class. Feel free to add your own cells and notes.

The git section of today's class (`git pull`, `git diff`) happens in your terminal, not in this notebook.

## Markdown in Jupyter Notebooks

Change a cell's type to Markdown (`Esc` then `m`) to write formatted notes instead of code.

Use Markdown cells to narrate your notebook: state the question you're answering before a code cell, and summarize what you found after it.

### Practice (5 min)

Let's work on these questions:

1. Add a Markdown cell with a heading for today's module and a one-sentence description of what we'll cover.
2. Add a bullet list of the git commands we used today, formatting each one as `inline code`.
3. Add a link to the [NumPy documentation](https://numpy.org/doc/stable/).

*1. Your Markdown here*

*2. Your Markdown here*

*3. Your Markdown here*

## Intro to NumPy

NumPy's own data type is the `numpy.ndarray`, an n-dimensional array. In Python you can alias an import using the `as` keyword. A common practice is to refer to `numpy` as `np`.

In [1]:
import numpy as np

`arr` has some important attributes:

- `ndim`: number of dimensions
- `shape`: the dimensions of the array
- `dtype`: the data type of the array

In [2]:
arr = np.array([1, 2, 3, 4])
arr.ndim, arr.shape, arr.dtype

(1, (4,), dtype('int64'))

### Some common arrays you can use

In [3]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones(3)

array([1., 1., 1.])

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Practice (5 min)

Let's work on these questions:

1. Create a 3 × 4 array of zeros with `np.zeros()`. Check its `shape`, `ndim`, and `dtype`.
2. Use `np.arange()` to create the even numbers from 0 to 20. Is 20 included?
3. Use `np.linspace()` to create 11 evenly spaced values from 0 to 1. What's the step between them?

In [1]:
# 1.
zero_array = np.zeros((3, 4))

zero_array.shape, zero_array.ndim


NameError: name 'np' is not defined

In [15]:
# 2.
even_num = np.arange(0, 20, 2)
even_num

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
# 3.
eleven = np.linspace(0, 1, 11)
eleven

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Random Numbers and Simulations

`rng.random()` draws a float uniformly between 0 and 1. Passing a seed to `default_rng()` makes your random draws reproducible.

In [18]:
rng = np.random.default_rng()
rng.random()

0.564314036000139

In [19]:
rng = np.random.default_rng(seed=42)
rng.random()

0.7739560485559633

### Other Ways to Draw Random Values

In [20]:
rng = np.random.default_rng(seed=42)

rng.integers(1, 7, size=10)          # 10 simulated die rolls

array([1, 5, 4, 3, 3, 6, 1, 5, 2, 1])

In [21]:
rng.choice(["heads", "tails"], size=10)  # 10 simulated coin flips

array(['tails', 'tails', 'tails', 'tails', 'tails', 'tails', 'tails',
       'heads', 'tails', 'heads'], dtype='<U5')

In [22]:
rng.normal(loc=0, scale=1, size=10)  # 10 draws from a standard Normal

array([ 0.87939797,  0.77779194,  0.0660307 ,  1.12724121,  0.46750934,
       -0.85929246,  0.36875078, -0.9588826 ,  0.8784503 , -0.04992591])

### Simple Simulations

`rolls == 6` gives an array of `True`/`False`. `True` counts as 1 and `False` as 0, so the mean is the proportion of rolls that were a 6.

In [23]:
rng = np.random.default_rng(seed=42)

rolls = rng.integers(1, 7, size=10_000)
(rolls == 6).mean()   # estimated probability of rolling a 6

np.float64(0.1625)

### Practice (5 min)

Let's work on these questions:

1. Simulate flipping a fair coin 1,000 times using `rng.choice()`. What proportion came up heads?
2. Simulate rolling two dice 10,000 times (two arrays of rolls, added together). Estimate the probability that the sum is 7.
3. Use `rng.normal()` to simulate 1,000 measurements with a mean of 100 and a standard deviation of 15. Compute the mean and standard deviation of your simulated sample — how close are they to the parameters you used?

In [32]:
# 1.
coin_flip = rng.choice(["heads", "tails"], size=1000)  # 10 simulated coin flips
head_count = 0
for coin in coin_flip:
    if coin == 'heads':
        head_count+= 1

print(head_count/1000)

0.507


In [45]:
# 2.
rng = np.random.default_rng(seed=42)

rng_one = rng.integers(1, 7, size=10000)
rng_two = rng.integers(1, 7, size=10000)

counter = 0
count_of_7 = 0
for i in rng_one:
    counter += 1
    if rng_one[i] + rng_two[i] == 7:
        count_of_7 += 1

print (count_of_7/counter)

0.3343


In [ ]:
# 3.


## Array manipulation

`.reshape()` changes the shape of an array. `.ravel()` flattens it into a 1-d array.

In [ ]:
arr = np.arange(24)
arr.reshape(4, 6)

In [ ]:
arr.reshape(2, 4, 3)

In [ ]:
arr.reshape(4, 6).ravel()

`axis=0` sums down the rows, giving one result per column. `axis=1` sums across the columns, giving one result per row.

In [ ]:
arr = np.arange(24).reshape(4, 6)
arr.sum(axis=0).shape   # (6,): one sum per column

In [ ]:
arr.sum(axis=1).shape   # (4,): one sum per row

### Practice (5 min)

Let's work on these questions:

1. Create `arr = np.arange(24)` and reshape it to `(4, 6)`, then to `(2, 3, 4)`. What happens if you try `(5, 5)`?
2. Predict the shapes of `arr.reshape(4, 6).sum(axis=0)` and `.sum(axis=1)`, then check.
3. Try `.cumsum(axis=1)` on the `(4, 6)` array. How is it different from `.sum(axis=1)`?

In [5]:
# 1.

import numpy as np
arr = np.arange(24)
arr.reshape(4, 6)
arr.reshape(2, 3, 4)
# arr.reshape (5,5) does not work because it is 24 things not 25 so not enough elements -> fail to execute

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [6]:
# 2.
arr.reshape(4, 6).sum(axis=0)
# 6 columns -> 6 values

array([36, 40, 44, 48, 52, 56])

In [7]:
arr.reshape(4, 6).sum(axis=1)
# 4 rows -> 4 values

array([ 15,  51,  87, 123])

In [8]:
# 3.
arr.reshape(4, 6).cumsum(axis=1)
# cumlative sum!

array([[  0,   1,   3,   6,  10,  15],
       [  6,  13,  21,  30,  40,  51],
       [ 12,  25,  39,  54,  70,  87],
       [ 18,  37,  57,  78, 100, 123]])

### Broadcasting

Multiplying arrays with `*` is element-wise; `@` is matrix multiplication. Broadcasting works between two arrays if their trailing dimensions are equal, or one of them is 1.

In [9]:
arr = np.arange(24).reshape([8, 3])
scaler = np.array([1, 2, 3])
new_arr = arr * scaler
new_arr

array([[ 0,  2,  6],
       [ 3,  8, 15],
       [ 6, 14, 24],
       [ 9, 20, 33],
       [12, 26, 42],
       [15, 32, 51],
       [18, 38, 60],
       [21, 44, 69]])

### Combining arrays

`np.hstack()` stacks arrays side by side, adding columns. `np.vstack()` stacks them on top of each other, adding rows. Both take a single tuple or list of arrays.

In [10]:
a = np.arange(6).reshape(2, 3)
np.hstack((a, a)).shape   # (2, 6)
# hstack horizontally stacks arrays side by side adding columns

(2, 6)

In [11]:
np.vstack((a, a)).shape   # (4, 3)
# vstack stacks vertically on top of each other adding rows

(4, 3)

### Practice (5 min)

Let's work on these questions:

1. Create `a = np.arange(6).reshape(2, 3)`. Predict, then check, the shapes of `np.hstack((a, a))` and `np.vstack((a, a))`.
2. Multiply `a` by `np.array([1, 10, 100])`. Which dimension was broadcast?
3. Write a function `duplicate(values, direction)` that turns a list into an array and repeats it:
   - `duplicate([1, 2, 3], "horizontal")` returns `[1, 2, 3, 1, 2, 3]`
   - `duplicate([1, 2, 3], "vertical")` returns `[[1, 2, 3], [1, 2, 3]]`
   - `duplicate([1, 2, 3], None)` returns `[1, 2, 3]`

In [13]:
# 1.
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
np.hstack((a, a))
# (2,3) and (2,3) next to each other

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [15]:
np.vstack((a, a))
# (2,3) above (2,3) 

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [16]:
# 2.
a*np.array([1, 10, 100])

array([[  0,  10, 200],
       [  3,  40, 500]])

In [18]:
# 3.
def duplicate(values, direction):
    values = np.array(values)
    if direction == 'horizontal':
        return np.hstack((values, values))
    elif direction == 'vertical':
        return np.vstack((values, values))
    else:
        return values
 